### ISSUE TITLE
Slow speed on here docs

### ISSUE THREAD

**Issue by fritzduchardt** [zdharma-continuum/fast-syntax-highlighting#5]
Love the tool, but facing slow performance on larger here docs, e.g.:

```
cat > /tmp/test <<EOF                                                                                                            (admin/default)..                                                                                                                                                                        
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: postgres
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: Always
          restartPolicy: Always
          env:
            - name: "PGDATA"
              value: "/var/lib/postgresql/data"
            - name: "POSTGRES_INITDB_WALDIR"
              value: "/var/lib/postgresql/dblogs/logs"
          ...
          ports:
            - name: port5432
              containerPort: 5432
          volumeMounts:
            - name: test
              mountPath: /var/lib/postgresql
            - name: postgressecret
              mountPath: /etc/postgressecret
              readonly: true
      volumes:
        - name: postgressecret
          secret:
            secretName: postgressecret
        - name: test
          persistentVolumeClaim:
            claimName: test
  volumeClaimTemplates:
    - metadata:
        name: test
        annotations:
          volume.beta.kubernetes.io/storage-class: thin-disk
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 20Gi
EOF
```
